export const REQUEST_POST_QUOTE = "REQUEST_POST_QUOTE"
export const POST_QUOTE_SUCCESS = "POST_QUOTE_SUCCESS"
export const POST_QUOTE_FAILURE = "POST_QUOTE_FAILURE"

export const REQUEST_PUT_QUOTE = "REQUEST_PUT_QUOTE"
export const PUT_QUOTE_SUCCESS = "PUT_QUOTE_SUCCESS"
export const PUT_QUOTE_FAILURE = "PUT_QUOTE_FAILURE"